### ISSUE TITLE
运行按关键词抓取新闻时报UnicodeDecodeError

### ISSUE THREAD

**Issue by feizei2008** [gaussic/baidu_hot_words#1]
Traceback (most recent call last):

  File "<ipython-input-4-186870552151>", line 1, in <module>
    runfile('C:/Users/Zack Zhang/Desktop/百度新闻抓取.py', wdir='C:/Users/Zack Zhang/Desktop')

  File "d:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "d:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Zack Zhang/Desktop/百度新闻抓取.py", line 19, in <module>

UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 0: ordinal not in range(128)

运行环境为windows7，anaconda4.1.1（32bit），请问是什么原因呢？感谢！

**Comment by gaussic** [comment]
@feizei2008 你好，你贴的代码看不到报错的那一行。初步判定是编码的问题，你尝试着在 文件顶部加上如下代码：

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

如果依然不行，请贴出完整代码

**Comment by feizei2008** [comment]
![_20170712225445](https://user-images.githubusercontent.com/18046390/28124064-36f8b8c2-6755-11e7-9d7c-4bea6dc1a775.png)

另外我把第12行的news_base_url改为'http://news.baidu.com/?tn=news' 后，运行结果如第二幅图所示，是不是百度新闻的规则有变化了呢？
![default](https://user-images.githubusercontent.com/18046390/28124398-21dee4ec-6756-11e7-95f0-912829a026f3.png)

**Comment by gaussic** [comment]
@feizei2008 

使用以下代码是完全没有问题的：

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

import requests
from bs4 import BeautifulSoup
import urllib


query_word = '43人中国旅行团护照在瑞典被抢'    
news_base_url = 'http://news.baidu.com/ns?tn=news'

news_url = news_base_url + query_word
parameters = {'word': query_word}

# 获取 JSON 数据
r = requests.get(news_base_url, params=parameters)
print(r.url)


soup = BeautifulSoup(r.text, 'lxml')
news_html_list = soup.select('div.result')
news_list = []
for news_html in news_html_list:
    news = {}
    news['标题'] = news_html.a.get_text().strip()
    news['链接'] = news_html.a['href']
    source = news_html.find('p', 'c-author').get_text().strip().replace('\xa0\xa0', ' ').split(' ')
    news['来源'] = source[0]
    news['发布日期'] = source[1]
    
    news_list.append(news)

for news in news_list:
    print(news)
```

你的问题应该出在 get_text() 这里有编码异常。这个请自行查找，因为我这边无法复现。

另外，url不用改，规则没有变，输出的url是经过编码了的。

**Comment by feizei2008** [comment]
确实是get_text()编码有问题，我直接把这几行注释掉，只取新闻的标题和链接，还是可以用的。非常感谢！
